### ISSUE TITLE
Feature Request - Erweiterung mit weiteren Infos (availablity, latency, ISP, uptime, version,...)

### ISSUE THREAD

**Issue by Brovning** [elueckel/Unifi-Toolbox#1]
- WAN1 availability
- WAN1 latency-average
- WAN1 time-period
- WAN2 availability
- WAN2 latency-average
- WAN2 time-period
- ISP Name
- ISP Organization
- Unifi Network Version
- Update available
- Update downloaded
- Uptime
- UBNT Device Type
- UDM Version

![image](https://user-images.githubusercontent.com/39644775/132350970-b7c7071e-5d9a-4250-9e41-40a12a9a81ed.png)

**Comment by Brovning** [comment]
Ich habe mal zum Testen einen Unifi Controller in einem Docker eingerichtet.

Rückgabe:
```
Array
(
    [meta] => Array
        (
            [rc] => ok
        )

    [data] => Array
        (
            [0] => Array
                (
                    [_id] => 5bf956ead2e924255c67c32f
                    [name] => default
                    [desc] => Brovning
                    [attr_hidden_id] => default
                    [attr_no_delete] => 1
                    [location_lat] => xxx
                    [location_lng] => xxx
                    [location_accuracy] => 0
                    [anonymous_id] => xxx
                    [health] => Array
                        (
                            [0] => Array
                                (
                                    [subsystem] => wlan
                                    [status] => unknown
                                    [num_ap] => 0
                                    [num_adopted] => 0
                                    [num_disabled] => 0
                                    [num_disconnected] => 0
                                    [num_pending] => 0
                                )

                            [1] => Array
                                (
                                    [subsystem] => wan
                                    [num_gw] => 0
                                    [num_adopted] => 0
                                    [num_disconnected] => 0
                                    [num_pending] => 0
                                    [status] => unknown
                                )

                            [2] => Array
                                (
                                    [subsystem] => www
                                    [status] => unknown
                                )

                            [3] => Array
                                (
                                    [subsystem] => lan
                                    [status] => unknown
                                    [num_sw] => 0
                                    [num_adopted] => 0
                                    [num_disconnected] => 0
                                    [num_pending] => 0
                                )

                            [4] => Array
                                (
                                    [subsystem] => vpn
                                    [status] => unknown
                                )

                        )

                    [num_new_alarms] => 507
                )

        )

)
```

Folglich sind nur folgende auf der Dream verfügbar und müssen abhängig vom ausgewählten Controller ein-/ausgeblendet werden:
- WAN1availability
- WAN1latency_average
- WAN1time_period
- WAN2availability
- WAN2latency_average
- WAN2time_period
- isp_name
- isp_organization

**Comment by elueckel** [comment]
Die Public IP kommt vermutlich auch nicht mit oder irre ich mich?

**Comment by elueckel** [comment]
Bitte schau auch mal auf die Namen die Variablen - die sollte gleichförmig sein. Doku und Übersetzung mache ich gerne. 

Ich muss auch mal mit dem ganzen merging schauen. Da habe ich noch keinen kompletten Plan :-)

**Comment by elueckel** [comment]
Kann es auch sein, dass du die Form noch nicht angepasst hast - ich habe im Patch 3 noch nichts gefunden?

**Comment by elueckel** [comment]
Also m.E. Macht das Internet Controller Modul so wie es ist nur auf der dream Maschine Sinn. 

Für anderes habe ich noch eine Idee um Geräte generell zu überwachen.

**Comment by Brovning** [comment]
> Die Public IP kommt vermutlich auch nicht mit oder irre ich mich?

Doch, die hat er sich geholt:
![image](https://user-images.githubusercontent.com/39644775/132380717-9fc20c32-1005-44ce-9d98-26a28f874581.png)

**Comment by Brovning** [comment]
> Kann es auch sein, dass du die Form noch nicht angepasst hast - ich habe im Patch 3 noch nichts gefunden?

Locale und Form war mit im Patch1 eingecheckt, da es ja zusammengehört:
![image](https://user-images.githubusercontent.com/39644775/132380955-8872ada0-bbd7-4207-9f61-a1cc71baef0a.png)

![image](https://user-images.githubusercontent.com/39644775/132381049-fdae7c9a-d80b-4795-8c1e-934668996aed.png)

**Comment by Brovning** [comment]
Was hältst du hiervon:
![image](https://user-images.githubusercontent.com/39644775/132381439-29e7bf56-21e5-4695-8368-21457ff4397a.png)

Ansonsten würde ich es dynamisch machen, so dass der untere Teil nur erscheint, wenn DreamMachine ausgewählt wurde.

**Comment by elueckel** [comment]
Finde ich super … ich ziehe es morgen rüber.

**Comment by elueckel** [comment]
Ich habe Patch 1 bei mir auf Beta gezogen. Werden heute Nachmittag daran basteln, damit wir nicht doppelt arbeiten.  Melde mich.

Funktioieren tut es - der Authentication Check geht nicht (braucht aber vermutlich niemand) ... auch werden ich die UI noch etwas bearbeiten (kosmetik) plus Doku. 

Ich glaube das wird aber gut und es gibt endlich ein wartbares Unifi Modul ... Meine Tocher ist total begeistert das ich jetzt per Knopfdruck alle Geräte vom Internet trennen kann :-) ...

**Comment by Brovning** [comment]
Habe dir die Änderung aus dem Screenshot eingecheckt:
"Absatz "Nachfolgende Werte sind nur mit DreamMachine verfügbar" hinzugefügt"

**Comment by Brovning** [comment]
Habe noch ein paar Änderungen bei mir lokal.
Sobald du fertig bist, lade deine Änderungen in Beta hoch und gib kurz Bescheid, dann mache ich meine Verbesserungen auch noch mit rein.

**Comment by elueckel** [comment]
Schiebe es schon jetzt hoch … ich mache nachher noch einen Snapshot. Musste erstmal in den Garten

**Comment by Brovning** [comment]
Ok, habe es bei #7 unter Patch-2 mit eingecheckt.
Ist ein Pull-Request auf deinen Beta Branch.

**Comment by elueckel** [comment]
@Brovning ich habe jetzt unter Beta die 1.0 liegen. Kleine Änderungen, aber nichts wildes - außer das ich den Active entfernt, habe, da man es einfach via Timer steuern kann 0=aus (mache ich bei den anderen Modulen von mir auch so, deswegen würde ich das so lassen wollen). 

Eine Frage - es gibt da den Betrachtungszeitraum, mit 86400 ... was macht der denn? :-)

**Comment by Brovning** [comment]
> Eine Frage - es gibt da den Betrachtungszeitraum, mit 86400 ... was macht der denn? :-)

Der Betrachtungszeitraum gibt an, auf welcher Basis die Verfügbarkeit in Prozent berechnet wurde.

**Comment by elueckel** [comment]
ok ... dann sind die 86400 Sekunden = 24h ... ich rechne das mal um, da die Zahl etwas nichtssagend ist.

**Comment by Brovning** [comment]
Eine Änderung hätte ich noch vorgeschlagen:
https://github.com/elueckel/Unifi-Toolbox/commit/30c3b613393426729868328f499dc8cbcbd5b867

**Comment by elueckel** [comment]
Cool - habe ich eingebaut hier und in der Anwesenheit (kommt auch in andere Module!

Ich habe auch noch Profile für Sekunden und Millisekunden hinzugefügt.

**Comment by elueckel** [comment]
So - ist nach Main gemerged ... nachdem ich den Merge versaut hatte (danke Github). Sollte alles gehen und die aktuellen Änderungen enthalten. 

Den Beta Branch setze ich neu auf sobald alles getestet ist.

**Comment by Brovning** [comment]
Hallo @elueckel ,
habe aktualisiert und getestet.
Funktioniert soweit alles.

**Comment by elueckel** [comment]
Top ... ich habe das Template für die 1.0 im Module Store gerade angelegt. Mal schauen ob noch Feedback kommt. 

Danke für Deine Unterstützung!!!! 

Ich habe noch weitere Ideen, aber mal schauen ob es requests gibt - bauen um das Bauenswillen muss ja nicht sein :-)

**Comment by Brovning** [comment]
Kein Problem, gerne wieder!
Ich sage danke fürs aufnehmen meiner Änderungen.
Du bist einer der Wenigen die das bisher gemacht haben. Die Meisten haben den Sinn von Git noch nicht verstanden... ;-)
