### ISSUE TITLE
Beibehalten der Werte beim IP Block geht nicht

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#12]

**Comment by Brovning** [comment]
Hallo @elueckel ,

Was meinst du hiermit?
Hast du ein paar Details für mich?

**Comment by elueckel** [comment]
War nicht für dich. Ich muss bei dem device blocker einiges umbauen.

**Comment by Brovning** [comment]
Ok, passt.
Ansonsten hätte ich versucht bei der Fehleranalyse zu helfen.

**Comment by elueckel** [comment]
Ich muss das ein wenig umbauen - ist aber vermutlich nicht super tragisch. Ich melde mich und danke für das Angebot 👍
