### ISSUE TITLE
Health Issue

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#18]
@Brovning Frohes Fest :-) 

Ich habe gerade nochmal nach dem einen Fehler geschaut der im Forum gemeldet wurde und oben die Deklaration aus der Funktion genommen. Das Modul geht ja eh nur mit Dream Maschines. 

Was aber komisch ist ist der Umstand, das bei mir beim Testen ein Fehler in der #323 in Bezug auf Health kommt. Da stimmt was nicht - kommen die Healthdaten nicht immer? Hast du eine Idee?

**Comment by elueckel** [comment]
ok - ich glaube ich bin für den Fehler verantwortlich. Ich habe ja im oberen Teil Deinen Code verändert und der wird unten vermisst. Kannst Du da bitte nochmal schauen wie wir den Fehler der bei der Installation kommt weg bekommen?

**Comment by elueckel** [comment]
ich sage jetzt nichts mehr ... :-) ... issue closed ... ich trink ein Bier

**Comment by Brovning** [comment]
Hallo @elueckel,

hast du den Fehler gefunden, da noch kein Checkin verlinkt ist?
Wenn ja, was war der Fehler?

**Comment by elueckel** [comment]
Moin,
ich habe es gestern schon eingechecked. Es fehlte das "string" vor der Variable - php will das sie deklariert ist. 

public function AuthenticateAndGetData (**_string_** $UnifiAPI = "") {

**Comment by Brovning** [comment]
👍
