### ISSUE TITLE
cleanup of the different modules in the toolbox required

### ISSUE THREAD

**Issue by Brovning** [elueckel/Unifi-Toolbox#23]
The modules are very similar, but they are all slightly different implemented.

I will try to do a cleanup over all modules.
Review required afterwards.

**Comment by elueckel** [comment]
Moin @Brovning,
die Module sollten eigentlich bis auf den Blocker weitgehend gleich sein und die Unterschiede marginal. Ich würde die 1.2 gerne dann mal abschließen und einreichen damit wir den aktuell Stand auf Prod. haben. 
Was denkst du?

**Comment by Brovning** [comment]
Ja, es sind nur Kleinigkeiten, aber mittlerweile sehr zahlreich...
Bitte führe ein Review der Änderungen durch und führe den Merge anschließend durch.
Danach kannst du das Ganze gerne auf Main übernehmen.

**Comment by elueckel** [comment]
OK 1.2 ist jetzt in Main und Cleanup gelöscht. 

Ich reiche ein - danke für die Mithilfe. Alleine hätte ich das so nicht hinbekommen!
