### ISSUE TITLE
Library for common functions

### ISSUE THREAD

**Issue by Brovning** [elueckel/Unifi-Toolbox#26]
Habe damit begonnen Funktionen in eine Library auszulagern, damit man diese nur an einer Stelle warten muss.
Das habe ich jetzt mal in einer Stunde gemacht, und darf gerne erweitert/verbessert werden. 👍

**Comment by elueckel** [comment]
Ich habe mir mal die Funktionen angeschaut ... sieht gut aus, wobei ich nicht so richtig weis wie ich sie testen sollte. 

Es müssten noch die Readme's upgedatet werden und dann könnten wir evtl direkt die 1.3 in den Module store pushen. 

Den Fehler mit dem nicht verbundenen Gerät sollte ich abgefangen haben.

**Comment by Brovning** [comment]
Das Beste wäre vermutlich, wenn wir es erst in den Beta-Branch mergen und 2-3 Tage auf Feedback warten, bevor es in den Main-Branch geht.

**Comment by Brovning** [comment]
DB ist meiner Meinung nach i.O..

Es kommt ein Fehler beim IC:
![image](https://user-images.githubusercontent.com/39644775/147857543-2eb67c05-7905-4988-9036-0f8b4e6f2496.png)

Meldung beim PM nach Klick auf CheckPresence:
![image](https://user-images.githubusercontent.com/39644775/147857594-d7ccfca7-2bff-4567-b57c-ee829bd48e87.png)

**Comment by Brovning** [comment]
IC Fehler behoben. Funktioniert nun.

**Comment by Brovning** [comment]
So, nun sollten alle funktionieren.
Hatte das GetBuffer() vergessen zu entfernen...
