### ISSUE TITLE
Nutzung der Public-Funktionen

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#29]
Guten Morgen @Brovning,
bei dem Aufruf der Funktionen müssen wir noch die Doku erweitern, da ich noch nicht so richtig weis wie man diese von außen nutzt. Kannst du hierzu bitte mal ein Beispiel senden. 

Ich habe mal probiert: $toogle = UniFiDeviceBlocker_block(51689);

Wäre es nicht sinnvoller den Aufruf UniFiDeviceBlocker_Manager(51689, block) oder halt unblock?

Evtl. verstehe ich es auch falsch?

**Comment by Brovning** [comment]
Hallo @elueckel ,

die Doku habe ich schon ergänzt:
https://github.com/elueckel/Unifi-Toolbox/tree/main/UniFi%20Device%20Blocker#5-php-befehlsreferenz

Zuerst die InstanzId des Blockers dynamisch ermitteln (oder statisch setzen):
`$InstanzID = IPS_GetInstanceListByModuleID("{FC3E71F1-BF95-D45D-0676-BA3D10D02CB8}")[0];`

Anschließend die MAC-Adresse ausfindig machen und wie folgt aufrufen:
`DB_block($InstanzID, $DeviceMacAddress);`

**Comment by Brovning** [comment]
Hierfür ist die Abkürzung relevant, welche du in der module.json unter "prefix" definiert hast.
Ich persönlich hätte alle Abkürzungen mit "U" beginnen lassen.
Bspw.:
"UDB", anstatt "DB"

**Comment by elueckel** [comment]
Hi,
danke für die Infos - machen Sinn. Ich mache aktuell noch mal eine Review ob mir was auffällt. 

Das ausgliedern der Funktionen für Token und Daten in ein Bibliothek macht Sinn und schaut auch gut aus. Ich muss noch ein wenig die Zusammenhänge verstehen, aber da muss ich meine Programmierkenntnisse noch ausbauen. 

Den Ansatz mit den Funktionen finde ich auch sinnvoll. 

Den Wandel zu UDB könnte man machen, ist aber nochmal ein wenig Aufwand mit übersichtlichen Benefits oder übersehe ich hier etwas?

**Comment by Brovning** [comment]
> Den Wandel zu UDB könnte man machen, ist aber nochmal ein wenig Aufwand mit übersichtlichen Benefits oder übersehe ich hier etwas?

Wieso denkst du, dass es viel Aufwand ist?
Für DB muss man inkl. Doku an 4 Stellen ändern:
![image](https://user-images.githubusercontent.com/39644775/147871747-c1edaeae-855b-4ee4-92a8-90ad05697723.png)

Bei den anderen Modulen sollten es stets nur 2 Stellen sein.

**Comment by elueckel** [comment]
Gerne machen, wobei ich dann bei allen Modulen ein U davor packen würde. Dann ist es sauber. 

Ich teste gerade noch ob ich den Fehler beinm Wiederverbinden sehen kann der im Forum reported wurde. Wenn dann alles passt, gebe ich heute Abend die 1.3 an das Symcon Team.  Ich will das der Master mit dem Leak aus dem Store kommt.

**Comment by elueckel** [comment]
Kannst du das hier sehen https://github.com/elueckel/Unifi-Toolbox/projects/2?add_cards_query=is%3Aopen ... ist evtl. sinnvoll um Ideen zu sammeln. Evtl. sollten wir dieses Issue hier auch als Blog führen zur Abstimmung?

**Comment by Brovning** [comment]
> Gerne machen, wobei ich dann bei allen Modulen ein U davor packen würde. Dann ist es sauber.

Ist erledigt.

**Comment by Brovning** [comment]
Für Diskussionen und Abstimmungen, wäre folgende App vermutlich besser geeignet und müsste noch von dir unter Options aktiviert werden:
![image](https://user-images.githubusercontent.com/39644775/147872911-c4dc70d1-d213-4f1c-95fa-ab3e1fc0dd5a.png)

Das Wiki könntest du bei der Gelegenheit gleich deaktivieren.

**Comment by Brovning** [comment]
> Kannst du das hier sehen https://github.com/elueckel/Unifi-Toolbox/projects/2?add_cards_query=is%3Aopen ... ist evtl. sinnvoll um Ideen zu sammeln.

Ja, kann ich sehen.
Sehr gut! 👍

**Comment by Brovning** [comment]
> > Evtl. sollten wir dieses Issue hier auch als Blog führen zur Abstimmung?
> 
> Für Diskussionen und Abstimmungen, wäre folgende App vermutlich besser geeignet und müsste noch von dir unter Options aktiviert werden: ![image](https://user-images.githubusercontent.com/39644775/147872911-c4dc70d1-d213-4f1c-95fa-ab3e1fc0dd5a.png)
> 
> Das Wiki könntest du bei der Gelegenheit gleich deaktivieren.

@elueckel Was hältst du davon?
Entfernen wir das Wiki und fügen Discussions hinzu?

**Comment by elueckel** [comment]
Jo - ist aktiviert.
