### ISSUE TITLE
Endpoint Monitor geht nicht mehr

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#30]
Hi @Brovning, 
der Endpoint Monitor geht seit der Änderung auf die zentrale Lib nicht mehr. 

da müsste ein /stat/sta/{mac} gesendet werden und ich kann nicht erkennen das dies geschieht? Auf jeden Fall fragt das Modul nicht die eingetragenen Geräte ab.

**Comment by Brovning** [comment]
Ok, sehe ich mir an.
