### ISSUE TITLE
Device Blocker geht nicht mehr

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#49]
eine Variable wird angelegt aber wenn man diese schaltet passiert nichts

**Comment by elueckel** [comment]
@Brovning kannst du hier bitte mal schauen. Es scheint, dass die Standard Aktion nicht ausgewertet wird? Sie ist vorhanden beim Anlegen, aber die Variable kann nicht geändert werden bez. triggert keine Blockade. Das ging am Montag nocht.

**Comment by elueckel** [comment]
ist ab Zeile 74 nicht eine Dopplung von 53 vorhanden. Ich glaube da liegt einiges über einander.

**Comment by Brovning** [comment]
Sehe ich mir an.

**Comment by elueckel** [comment]
rest geht soweit ich das sehen kann

**Comment by Brovning** [comment]
Fehler gefunden.
Die RequestAction($Ident, $Value) ist bei irgendeinem Change verloren gegangen...
Bitte testen.
