### ISSUE TITLE
Rename Device Blocker to Endpoint Blocker

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#52]
### Discussed in https://github.com/elueckel/Unifi-Toolbox/discussions/51

<div type='discussions-op-text'>

<sup>Originally posted by **elueckel** January  5, 2022</sup>
Ich denke ich will den Device Blocker noch in Endpoint Blocker umbenennen (also nur Name). 

Endpoints sind Geräte während Device Teile von Unifi sind. Dann es er auch gleich mit dem Endpoint Monitor. Verzeichnis usw. würde ich gleiche lassen, sonst gibt es wieder Schmerzen beim Upgrade?

Was denkst du @Brovning </div>

**Comment by elueckel** [comment]
ok ... done ... auch der identifier ist jetzt UEB

**Comment by elueckel** [comment]
bin gespannt wie sehr das bei einem Update knallt :-)

**Comment by Brovning** [comment]
Du hast scheinbar beim Checkin vergessen die Nummer 52 anzugeben.
Habe ich im Kommentar nachgeholt, damit der Checkin verlinkt ist.

Das Update funktionierte bei mir ohne Fehler.
Lediglich die public function Aufrufe (sofern verwendet) müssen von UDB in UEB umbenannt werden.
Bspw.:
UDB_block($InstanzID, $device); → UEB_block($InstanzID, $device);

**Comment by Brovning** [comment]
@elueckel Du hast vergessen den Ordner umzubenennen.
Im Ordner "UniFi Device Blocker" befindet sich nun der "UniFi Endpoint Blocker".

**Comment by Brovning** [comment]
Ja. sehe ich auch so. Konfigurator wäre eine 2.0.
Alles andere, was kleinere Verbesserungen sind und auch die TestSuite kommen in eine 1.4.

**Comment by Brovning** [comment]
Habe es gestern noch geschafft alle nötigen PHP Funktionen für die TestSuite zu stubben und es hat ohne Fehler die TestSuite ausgeführt.
Jetzt müssen "nur" noch die ganzen Funktionen gefüllt werden, so dass der UnifiController simuliert wird...

**Comment by Brovning** [comment]
Verzeichnisumbenennung siehe #57
