### ISSUE TITLE
Korrektur für Einreichung

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#56]
die Einreichung Ihres Moduls UniFi Toolbox vom Konto elueckel wurde leider abgelehnt. Bitte überarbeiten Sie Ihre Einreichung noch einmal und reichen Sie diese erneut ein.
Als Grund für die Ablehnung nannte das Symcon Team:
In ApplyChanges erstellst du Variablen und setzt das benutzerdefinierte Profil von selbst erstellten Variablen. Dies liegt allerdings vollständig in der Hoheit des Benutzers und darf vom Modul nicht angepasst werden, siehe auch Punkt 11 der Reviewrichtlinien. Hierfür ist das Standardprofil vorgesehen. Daher solltest du deine Variable stattdessen per RegisterVariableBoolean (https://www.symcon.de/service/dokumentation/entwicklerbereich/sdk-tools/sdk-php/module/registervariableboolean/) erstellen. Damit kannst du alle Parameter von dir auch setzen, nur statt des benutzerdefinierten Profils das Standardprofil. Dies ist auch der vorgesehene Weg für Instanzen um die eigenen Variablen anzulegen.

**Comment by elueckel** [comment]
bin schon dran ...

**Comment by Brovning** [comment]
@elueckel bitte immer mit "#" und der Ticketnummer (in diesem Fall 56) die Checkins zu den Tickets verlinken.

**Comment by elueckel** [comment]
Geht klar … ich bin noch GitHub Neuling 👍
