### ISSUE TITLE
Umbenennung Verzeichnis Device to Endpoiont Blocker

### ISSUE THREAD

**Issue by elueckel** [elueckel/Unifi-Toolbox#57]
Prüfen was die Auswirkungen bei einem Update sind.

**Comment by elueckel** [comment]
@Brovning magst du bei dir auch bitte noch mal schauen ob die Beta Probleme macht beim Endpoint Blocker ... ich habe es getestet und es sollte alles passen, aber 4 Augen sehen mehr als 2 :-)

**Comment by Brovning** [comment]
Kann ich machen.
Wird aber abends werden.

**Comment by Brovning** [comment]
Fehler gefunden und behoben.
Ticket kann geschlossen werden.
