### ISSUE TITLE
Temp auslesen ?

### ISSUE THREAD

**Issue by Sasch600xt** [elueckel/Unifi-Toolbox#74]
Hallo zusammen,

ich versuche gerade die Temperaturen der UniFi APs auszulesen.
Mit PRTG habe ich es leider nicht hinbekommen.
Kann das eure Toolbox eventuell ?

Liebe Grüße
Sascha

**Comment by elueckel** [comment]
Aktuell nicht … war noch nie ein Thema Am 02.09.2023 um 21:21 schrieb Sasch600xt ***@***.***>:﻿
Hallo zusammen,
ich versuche gerade die Temperaturen der UniFi APs auszulesen.
Mit PRTG habe ich es leider nicht hinbekommen.
Kann das eure Toolbox eventuell ?
Liebe Grüße
Sascha

**Comment by Sasch600xt** [comment]
Ich hab 2 von den U6 Wall Versionen. Die werden echt warm/heiß. Einer hängt in der Gartenhütte, die dunkel gestrichen ist. Da können im Sommer schon mal 45 Grad herrschen, Ich wollte da eventuell für die Sommermonate eine Lüftersteuerung basteln, und da hätte mich die interne Temperatur der APs interessiert.

**Comment by elueckel** [comment]
es gibt leider keinen Wert für die Temperatur.
